apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dsv-app
  namespace: dsv
spec:
  # Max 12 nodes based on config. Missing nodes will stay pending (Standby behavior).
  replicas: 3
  serviceName: dsv-app-headless
  selector:
    matchLabels:
      app: dsv-app
  template:
    metadata:
      labels:
        app: dsv-app
    spec:
      containers:
        - name: dsv-app
          image: dsv-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4801
              name: cluster
            - containerPort: 9080
              name: http
          env:
            - name: SERVER_PORT
              value: "9080"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CLUSTER_PORT
              value: "4801"
            - name: SEED_DNS_HOST
              value: "dsv-app-headless.dsv.svc.cluster.local"
            - name: SEED_DNS_PORT
              value: "4801"
            # Sidecar redis is reachable via localhost
            - name: SPRING_DATA_REDIS_HOST
              value: "localhost"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              value: ""
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.dsv.svc.cluster.local:9092"
        # Redis Sidecar container within the same Pod
        - name: redis-sidecar
          image: redis:8.6-alpine
          ports:
            - containerPort: 6379
          command: ["redis-server", "--appendonly", "yes"]
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
